# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Calculator Workflow
on: [push]

jobs:
  run_calculator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run calculator-v2.py
      run: |
        python GitHub-Actions/calculator-v2.py ${{ choice }} ${{ x }} ${{ y }}
      env:
        choice: ${{ random.choice(["add", "subtract", "multiply", "divide"]) }}
        x: ${{ random.randint(-1000, 1000) }}
        y: ${{ random.randint(-1000, 1000) }}
