# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Calculator App

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run calculator-v2.py
      run: |
        python GitHub-Actions/calculator-v2.py $(python -c "import random;print(random.choice(['add', 'subtract', 'multiply', 'divide']))") $(python -c "import random;print(random.randint(1,10))") $(python -c "import random;print(random.randint(1,10))")

